all: q1 q2 q3 q4 q5 q7

q1: 2_1.cpp
	g++ -std=c++11 -Wall -o main 2_1.cpp

q2: 2_2.cpp
	g++ -std=c++11 -Wall -o main 2_2.cpp

q3: WindGauge.h WindGauge.cpp testWindGauge.cpp
	g++ -std=c++11 -Wall -o main WindGauge.cpp testWindGauge.cpp

q4: 2_4.cpp
	g++ -std=c++11 -Wall -o main 2_4.cpp

q5: 2_5.cpp
	g++ -std=c++11 -Wall -o main 2_5.cpp

q7: 2_7.cpp
	g++ -std=c++11 -Wall -o main 2_7.cpp