all: selectionSort 3_2d plot

selectionSort: selectionSort.cpp
	g++ -Wall -o selectionSort selectionSort.cpp

3_2d: 3_2d.cpp
	g++ -std=c++11 -Wall -o 3_2d 3_2d.cpp 

plot: plot.plt 
	gnuplot plot.plt 

