all: countingSort bucketSort radixSort

countingSort: countingSort.cpp
	g++ -std=c++11 -Wall -o countingSort countingSort.cpp

bucketSort: bucketSort.cpp
	g++ -std=c++11 -Wall -o bucketSort bucketSort.cpp
	
radixSort: radixSort.cpp
	g++ -std=c++11 -Wall -o radixSort radixSort.cpp
	