all: countingSort bucketSort radixSort words radixSortOld

countingSort: countingSort.cpp
	g++ -std=c++11 -Wall -o countingSort countingSort.cpp

bucketSort: bucketSort.cpp
	g++ -std=c++11 -Wall -o bucketSort bucketSort.cpp
	
radixSort: radixSort.cpp
	g++ -std=c++11 -Wall -o radixSort radixSort.cpp
	
words: words.cpp
	g++ -std=c++11 -Wall -o words words.cpp

radixSortOld: radixSortOld.cpp
	g++ -std=c++11 -Wall -o radixSortOld radixSortOld.cpp